import { existsSync, readFileSync, statSync } from "node:fs";
import { resolve } from "node:path";

// All configuration lives in config.json (gitignored), generated by
// config-gen.sh. There are deliberately no environment variables.

export interface HarnessConfig {
  enabled: boolean;
  command: string;
  /** Extra env for the harness process, merged over the server's own env.
   * Used by claude-local to point the CLI at a local OpenAI/Anthropic-compatible
   * endpoint (e.g. vLLM) via ANTHROPIC_BASE_URL + ANTHROPIC_DEFAULT_*_MODEL, so
   * chat sessions can be tested end-to-end without spending Claude tokens. */
  env?: Record<string, string>;
}

export interface LlmConfig {
  provider: string;
  baseUrl: string;
  model: string;
}

/** Which harness (and slash command) auto-PR drives to draft/open the PR. Kept
 * in config so the harness-agnostic core doesn't hardcode a harness id. */
export interface AutoPrConfig {
  /** Harness id to start for the PR session (default "pi"). */
  harness?: string;
  /** First prompt sent to it — a slash command or free text (default "/pr"). */
  instructions?: string;
  /** @deprecated legacy name for `instructions`. */
  command?: string;
}

/** Lifetime token-usage state file written by an external sampler (e.g. a cron
 * scraping vLLM /metrics), shown on the System state page. */
export interface TokenUsageConfig {
  /** Path to the JSON state file; `~` is expanded. */
  file: string;
  /** Cost-estimate pricing (USD per 1M tokens). Default: Claude Sonnet $3/$15. */
  pricing?: { label: string; inputPerM: number; outputPerM: number } | null;
}

export interface Config {
  harnesses: {
    claude: HarnessConfig;
    /** Optional second Claude adapter pointed at a local endpoint (via `env`)
     * for token-free end-to-end testing of the chat UI. Same adapter as
     * `claude`, different id/name/env. */
    claudeLocal?: HarnessConfig;
    pi: HarnessConfig;
    terminal: HarnessConfig;
  };
  llm: LlmConfig;
  /** Optional overrides for the auto-PR capability (see AutoPrConfig). */
  autoPr?: AutoPrConfig;
  tokenUsage?: TokenUsageConfig;
  /** Usernames allowed to log in. A registered account stays unusable until its
   * name appears here. */
  users: string[];
  /** Web signup. Default "closed": accounts come from `npm run add-user`, which
   * also enables them (no window for someone else to claim an enabled name). */
  registration?: "open" | "closed";
  server?: {
    port?: number;
  };
}

const CONFIG_PATH = resolve(process.cwd(), "config.json");

export function loadConfig(): Config {
  if (!existsSync(CONFIG_PATH)) {
    throw new Error(
      `config.json not found at ${CONFIG_PATH}.\n` +
        "Run ./config-gen.sh to generate it.",
    );
  }
  try {
    const config = JSON.parse(readFileSync(CONFIG_PATH, "utf8")) as Config;
    // Tolerate an older config.json with no users list; nobody is enabled.
    config.users ??= [];
    // Tolerate an older config.json with no llm block; default to local vLLM.
    config.llm ??= {
      provider: "vllm",
      baseUrl: "http://localhost:8000/v1",
      model: "default",
    };
    return config;
  } catch (err) {
    throw new Error(
      `Failed to parse config.json: ${(err as Error).message}`,
    );
  }
}

let usersCache: { mtimeMs: number; users: string[] } | null = null;

/** The enabled-user list, re-read from config.json when it changes, so
 * `npm run add-user` / removing a name applies without a restart (which would
 * kill every live session). Falls back to the startup list on any read error. */
export function enabledUsers(config: Config): string[] {
  try {
    const mtimeMs = statSync(CONFIG_PATH).mtimeMs;
    if (usersCache?.mtimeMs !== mtimeMs) {
      const raw = JSON.parse(readFileSync(CONFIG_PATH, "utf8")) as {
        users?: unknown;
      };
      const users = Array.isArray(raw.users)
        ? raw.users.filter((u): u is string => typeof u === "string")
        : [];
      usersCache = { mtimeMs, users };
    }
    return usersCache.users;
  } catch {
    return usersCache?.users ?? config.users;
  }
}

/** Path of config.json, for tools that edit it (scripts/add-user.ts). */
export const configPath = CONFIG_PATH;
