import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

// All configuration lives in config.json (gitignored), generated by
// config-gen.sh. There are deliberately no environment variables.

export interface HarnessConfig {
  enabled: boolean;
  command: string;
  /** Extra env for the harness process, merged over the server's own env.
   * Used by claude-local to point the CLI at a local OpenAI/Anthropic-compatible
   * endpoint (e.g. vLLM) via ANTHROPIC_BASE_URL + ANTHROPIC_DEFAULT_*_MODEL, so
   * chat sessions can be tested end-to-end without spending Claude tokens. */
  env?: Record<string, string>;
}

export interface LlmConfig {
  provider: string;
  baseUrl: string;
  model: string;
}

export interface Config {
  harnesses: {
    claude: HarnessConfig;
    /** Optional second Claude adapter pointed at a local endpoint (via `env`)
     * for token-free end-to-end testing of the chat UI. Same adapter as
     * `claude`, different id/name/env. */
    claudeLocal?: HarnessConfig;
    pi: HarnessConfig;
    terminal: HarnessConfig;
  };
  llm: LlmConfig;
  /** Usernames allowed to log in. A registered account stays unusable until its
   * name appears here. */
  users: string[];
  server?: {
    port?: number;
  };
}

const CONFIG_PATH = resolve(process.cwd(), "config.json");

export function loadConfig(): Config {
  if (!existsSync(CONFIG_PATH)) {
    throw new Error(
      `config.json not found at ${CONFIG_PATH}.\n` +
        "Run ./config-gen.sh to generate it.",
    );
  }
  try {
    const config = JSON.parse(readFileSync(CONFIG_PATH, "utf8")) as Config;
    // Tolerate an older config.json with no users list; nobody is enabled.
    config.users ??= [];
    // Tolerate an older config.json with no llm block; default to local vLLM.
    config.llm ??= {
      provider: "vllm",
      baseUrl: "http://localhost:8000/v1",
      model: "default",
    };
    return config;
  } catch (err) {
    throw new Error(
      `Failed to parse config.json: ${(err as Error).message}`,
    );
  }
}
