import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

// All configuration lives in config.json (gitignored), generated by
// config-gen.sh. There are deliberately no environment variables.

export interface HarnessConfig {
  enabled: boolean;
  command: string;
}

export interface LlmConfig {
  provider: string;
  baseUrl: string;
  model: string;
}

export interface Config {
  harnesses: {
    claude: HarnessConfig;
    pi: HarnessConfig;
    terminal: HarnessConfig;
  };
  llm: LlmConfig;
  server?: {
    port?: number;
  };
}

const CONFIG_PATH = resolve(process.cwd(), "config.json");

export function loadConfig(): Config {
  if (!existsSync(CONFIG_PATH)) {
    throw new Error(
      `config.json not found at ${CONFIG_PATH}.\n` +
        "Run ./config-gen.sh to generate it.",
    );
  }
  try {
    return JSON.parse(readFileSync(CONFIG_PATH, "utf8")) as Config;
  } catch (err) {
    throw new Error(
      `Failed to parse config.json: ${(err as Error).message}`,
    );
  }
}
