// Live end-to-end coverage of next-prompt suggestions (the predicted follow-up
// the Claude Code TUI shows). With `promptSuggestions:true` on query(), the
// `claude` CLI emits a `prompt_suggestion` message after each turn (never the
// first) carrying a predicted next user prompt; the adapter maps it to a
// `prompt-suggestion` ChatEvent that folds into ChatState.promptSuggestions.
//
// IMPORTANT — harness reality (see CLAUDE.md "run it live and adjust"): the
// suggestion is generated by an EXTRA model call the `claude` CLI makes, and it
// works against the real Anthropic endpoint (where the TUI shows it) but the
// local vLLM harness does NOT emit one — the small model errors on / doesn't
// satisfy that secondary call, and the SDK suppresses suggestions "after API
// errors". So the deterministic mapping/fold is pinned by pure reducer tests
// (`shared/chat.test.ts`); this live test asserts only that enabling the flag is
// SAFE (turns still complete) and probes for the suggestion best-effort, folding
// + asserting it only if one actually arrives (so it tightens automatically if
// the local model ever gains the capability, without flaking red today).
//
// Spends zero Claude tokens (hits the local vLLM endpoint), excluded from
// `npm test` (run via `npm run test:e2e`), self-skips unless claude-local is
// enabled and its endpoint answers.
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it, expect } from "vitest";
import { emptyChatState, applyChatEvent } from "../../shared/chat.js";
import type { ChatEvent } from "../../shared/protocol.js";
import { claudeLocal, endpointUp, ChatDriver, settle } from "./claude-local.testkit.js";

const DIR = mkdtempSync(join(tmpdir(), "agent-remote-e2e-"));

const local = claudeLocal();
const up = await endpointUp(local?.baseUrl);

describe.skipIf(!local || !up)("claude-local: next-prompt suggestion", () => {
  it("enabling promptSuggestions keeps turns healthy; folds a suggestion if emitted", async () => {
    const driver = new ChatDriver(local!.create(DIR)).start();
    // The suggestion (if any) is suppressed on the first turn, so do two and
    // then let the CLI's post-`result` suggestion call (if it makes one) land.
    await driver.prompt("What is 2 + 2? Answer with just the number.", 90_000);
    await driver.prompt("Now what is 3 + 3? Answer with just the number.", 90_000);
    await settle(8_000);
    driver.close();

    // Hard gate: enabling the flag didn't wedge the session — both turns
    // completed (a `busy:false` per turn) and none errored out.
    const idles = driver.events.filter((e) => e.type === "busy" && !e.busy);
    expect(idles.length).toBeGreaterThanOrEqual(2);

    // Best-effort: if the harness did emit a suggestion, it must be non-empty
    // and fold into ChatState.promptSuggestions through the shared reducer.
    const sugg = driver.events.find(
      (e): e is Extract<ChatEvent, { type: "prompt-suggestion" }> =>
        e.type === "prompt-suggestion",
    );
    if (sugg) {
      expect(sugg.suggestions.length).toBeGreaterThan(0);
      expect(sugg.suggestions.every((s) => s.trim().length > 0)).toBe(true);
      let state = emptyChatState();
      for (const e of driver.events) state = applyChatEvent(state, e);
      expect(state.promptSuggestions).toEqual(sugg.suggestions);
    } else {
      console.warn(
        "[claude-suggestion.e2e] local harness emitted no prompt_suggestion " +
          "(expected — the secondary suggestion call needs the real endpoint). " +
          "Mapping/fold is covered by shared/chat.test.ts.",
      );
    }
  }, 210_000);
});
